### ISSUE TITLE
branches solution

### ISSUE THREAD

**Issue by eseguro** [jdjuan/your-first-angular-application#1]
https://github.com/eseguro/angular-medellin-execise1/

**Comment by jdjuan** [comment]
Muy bien @eseguro !  🥇 
Disculpa la tardanza para responder 😅 sin embargo lo hiciste muy bien, felicitaciones! 🥇 

Te recomiendo esta forma de negar una variable la próxima ocasión: 👌 

`<button (click)="enabled = !enabled" >Change state</button>`
