### ISSUE TITLE
Challenge accepted!!

### ISSUE THREAD

**Issue by matew17** [jdjuan/your-first-angular-application#10]
Hey Angular Medellin, 

I accepted the challenge, now you can check the code below: 

 👇 👇 👇 

https://github.com/matew17/my-first-angular-app

Thanks 😸

**Comment by jdjuan** [comment]
Very good @matew17 ! 😁 

Excellent code, well organized and readable!

Pro tip: next time avoid naming variables as types (boolean) it works, but it can be confusing 😄
