### ISSUE TITLE
Mision imposible :fire:

### ISSUE THREAD

**Issue by Shinkei** [jdjuan/your-first-angular-application#7]
Hola, este es el repo con el taller de Angular Medellin "your-first-angular-application"
[repo](https://github.com/Shinkei/AngularProyecto0)

Gracias :grinning:

**Comment by jdjuan** [comment]
Wow wow wow! Excelente @Shinkei 🥇 
Disculpa la tardanza para responder 😅 Muy bien hecho! Se nota que le pusiste dedicación a la tarea. Felicitaciones! 🥇 Muy bien! De verdad! Sigue así! 😸  👌
