### ISSUE TITLE
¡Mission complete!

### ISSUE THREAD

**Issue by brianou7** [jdjuan/your-first-angular-application#8]
[https://github.com/brianou7/first-angular-application](https://github.com/brianou7/first-angular-application)

**Comment by jdjuan** [comment]
Excelente @brianou7  🥇 
Disculpa la tardanza para responder 😅 Lo hiciste muy bien! Felicitaciones! 👍 Veo que es tu primer repo en GitHub! Súper! 🤙 

Vi que utilizaste un método para cambiar el valor de la variable, muy bien!, ése es un buen patrón! La próxima vez puedes hacer la siguiente mejora:

Reemplazar esto:

```
if (this.enabled){
      this.enabled = false;
    }else{
      this.enabled = true;
    }
```

Por esto:
```
this.enabled = !this.enabled;
```

Sigue así! 😸  👌

**Comment by brianou7** [comment]
Gracias @jdjuan por la recomendación, la verdad es que soy algo nuevo en Angular y tambien en Github, soy un desarrollador back-end y apenas estoy incursionando en el mundo del front-end, he visto un poco de Vue y Agunlar y llaman bastante mi atención; Para no hacer este comentario más largo (jajaja), es mi primer repositorio en githun pues acostumbro manejar bitbucket, y aunque mifuerte es el desarrollo web con python, estoy dispuesto a ayudar en lo que sea posible.

De nuevo gracias por tomarte el tiempo de revisar el taller!

**Comment by jdjuan** [comment]
@brianou7 ! Excelente! Aquí estamos para aprender!
Gracias por ofrecer tu ayuda! 👍 Nos vemos en el próximo meetup! 👌
