### ISSUE TITLE
Solución Taller

### ISSUE THREAD

**Issue by angelitaooo** [jdjuan/your-first-angular-application#9]
Hola Juan, aquí está mi solución del taller.

https://github.com/angelitaooo/project1-meetup-angular

Gracias!

**Comment by jdjuan** [comment]
@angelitaooo ! me dice página no encontrada 😲 😧

**Comment by angelitaooo** [comment]
Qué pena es que lo tenía privado!

Acá se puede ver también https://angelitaooo.github.io/project1-meetup-angular/

Gracias!!!

**Comment by jdjuan** [comment]
Súper bien! 🥇 incluso lo pusiste online! 👌 

Felicitaciones! 🌵 🌵 🌵 Un código impecable!
